package cz.phsoft.hokej.models.dto;

import cz.phsoft.hokej.data.enums.PlayerType;
import cz.phsoft.hokej.data.enums.Role;

public class PlayerDTO {

    private Long id; // autogenerated, nullable při create
    private String name; // not null
    private String surname; // not null
    private String fullName; // derived
    private String email; // not null
    private String phone; // nullable
    private PlayerType type; // not null, default BASIC
    private Role role; // not null, default PLAYER
    private boolean enabled; // default false

    public PlayerDTO() {
        this.type = PlayerType.BASIC;
        this.role = Role.PLAYER;
        this.enabled = false;
    }

    public PlayerDTO(Long id, String name, String surname, String email, String phone,
                     PlayerType type, Role role, boolean enabled) {
        this.id = id;
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.phone = phone;
        this.type = type != null ? type : PlayerType.BASIC;
        this.role = role != null ? role : Role.PLAYER;
        this.enabled = enabled;
        this.updateFullName();
    }

    // --- Gettery a Settery ---

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; updateFullName(); }

    public String getSurname() { return surname; }
    public void setSurname(String surname) { this.surname = surname; updateFullName(); }

    public String getFullName() { return fullName; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPhone() { return phone; }
    public void setPhone(String phone) { this.phone = phone; }

    public PlayerType getType() { return type; }
    public void setType(PlayerType type) { this.type = type != null ? type : PlayerType.BASIC; }

    public Role getRole() { return role; }
    public void setRole(Role role) { this.role = role != null ? role : Role.PLAYER; }

    public boolean isEnabled() { return enabled; }
    public void setEnabled(boolean enabled) { this.enabled = enabled; }

    private void updateFullName() {
        this.fullName = name + " " + surname;
    }
}
